### ISSUE TITLE
cterm colors are off

### ISSUE THREAD

**Issue by gobenji** [naquad/vim-picker#2]
Hi, the functionality in this script is great, I especially love the color wheel but the cterm (xterm-256color) numbers and respective RGB components seem to be off.
For example, if I use the output from the script here
https://www.vim.org/scripts/script.php?script_id=1349
color 154 is af/ff/00, "GreenYellow"
but vim-picker shows color 154 as #D70000, a kind of brick red.

**Comment by naquad** [comment]
Hi, sorry for the long reply.

Color palettes can be found in [palettes.py](https://github.com/naquad/vim-picker/blob/master/palettes.py) and to make it equal to colortest one would have to update them.
For a VIM user it should be a piece of cake ;)

I don't have much time to spend on this project so contributions are welcome :)
